# Task 2: Normalize Breadboard Images

In [19]:
%load_ext autoreload
%autoreload 2

from breadboard_normalizer.normalizer import Normalizer, PinGrid, draw_corners, resize_width, image_label_pairs

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [20]:
normalizer = Normalizer(padding=[0.0, 0.0], output_resolution=0.5)


Creating pingrid with 830 points and 830 labels


In [28]:
import cv2
import numpy as np
from PIL import Image, ImageOps
import os

# image = Image.open("example_training_images/4b6949fe-0ae765d4-69E2A987-8D4F-4075-A989-01B6BA302390.jpeg")

image_dir = "example_training_images/"

window_name = "annotated image"
cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)

for index, file in enumerate(os.listdir(os.fsencode(image_dir))):
    filename, ext = os.path.splitext(os.fsdecode(file))
    if ext.lower().endswith(Normalizer._image_extensions):
        image_pil = Image.open(image_dir + filename + ext)
        image_pil = ImageOps.exif_transpose(image_pil)
        image = np.array(image_pil)

        norm, source_corners, score = normalizer.normalize_image(image, registration="icp")

        if norm is None:
            continue
        
        point_color = (0, 255, 0)
        if score < 0.5:
            point_color = (0, 0, 255)
        elif score <= 0.75:
            point_color = (0, 255, 255)

        h = cv2.getPerspectiveTransform(source_corners, normalizer.destination_corners)
        h_inv = np.linalg.inv(h)

        source_points = PinGrid.transform_points_3x3(normalizer.pingrid.points, h_inv)

        if norm is None:
            print("Failed to normalize image")
        else:
            # CV2 assumes BGR
            norm = np.flip(norm, axis=-1)
            image = np.flip(image, axis=-1)

            image = draw_corners(image, source_corners)

            for x, y in normalizer.pingrid.points:
                norm = cv2.circle(norm.astype(np.uint8), (int(x), int(y)), 2, point_color, -1)
            
            for x, y in source_points:
                image = cv2.circle(image, (int(x), int(y)), 16, point_color, -1)

            image = resize_width(image, normalizer.target_size[0])

            image = np.vstack([image, norm])

            cv2.imshow(window_name, image)
            if cv2.waitKey(0) == ord('q'):
                break
cv2.destroyAllWindows()

Refinement transform failed.
Refinement transform failed.
Refinement transform failed.
Refinement transform failed.
Refinement transform failed.


In [168]:
import cv2
cv2.destroyAllWindows()

In [58]:




def webcam_demo():
    # 1. Initialize the webcam (0 is typically the default camera)
    cap = cv2.VideoCapture(1)

    fourcc = cv2.VideoWriter_fourcc(*'mp4v')

    out = None

    if not cap.isOpened():
        print("Error: Could not open webcam.")
        return

    corner_history = np.zeros((4, 4, 2), dtype = np.float32)
    label_history = np.zeros((8), dtype=int)
    i = 0

    window_name = "Webcam Demo"
    cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)

    while True:
        # 2. Capture frame-by-frame
        # ret is a boolean (True if frame is captured), frame is the image array
        ret, frame = cap.read()

        frame_scaled = resize_width(frame, normalizer.target_size[0])

        if not ret:
            print("Error: Can't receive frame. Exiting ...")
            break

        frame_rgb = np.flip(frame, axis=-1)
        # source_corners = normalizer.find_corners(frame_rgb)


        # norm_bgr = np.zeros((normalizer.target_size[1], normalizer.target_size[0], 3), dtype=np.uint8)


        # if source_corners is None:
        #     source_corners = corner_history[i % 4]
        # if source_corners is not None:
        #     i += 1

        # corner_history[i % 4] = source_corners

        # norm = normalizer.warp_image(frame_rgb, source_corners)

        # label = normalizer.breadboard_orientation_cv(norm)
        # # label = 'correct'

        # if label == 'flipped':
        #     label_history[i % 8] = 1
        # else:
        #     label_history[i % 8] = -1

        # if np.sum(label_history) > 0:
        #     norm = np.flipud(norm)
        #     source_corners = np.flip(source_corners, axis=0)

        # frame = draw_corners(frame, source_corners)
        # frame_scaled = resize_width(frame, normalizer.target_size[0])

        # norm_bgr = np.flip(norm, axis=-1)
        
        # cv2.imshow('Webcam Demo', np.vstack([frame_scaled, norm_bgr]))
        annotated = normalizer._show_ml_annotated_image(frame_rgb, window_name)

        if annotated is None:
            continue
        
        if out is None:
            out = cv2.VideoWriter('recordings/output_2.mp4', fourcc, 20.0, (annotated.shape[1], annotated.shape[0]))
        
        out.write(annotated)

        # 4. Press 'q' on the keyboard to exit
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    # 5. Release resources
    cap.release()

    out.release()
    cv2.destroyAllWindows()


In [59]:
webcam_demo()

[[0.99099505]
 [0.9938261 ]
 [0.86819947]
 [0.9858828 ]]
[ True  True  True  True]
[[0.9847767 ]
 [0.99399704]
 [0.9877942 ]
 [0.98098856]]
[ True  True  True  True]
[[0.9758471 ]
 [0.99570924]
 [0.99415404]
 [0.9739423 ]]
[ True  True  True  True]
[[0.9933025]
 [0.9943206]
 [0.9877799]
 [0.9779992]]
[ True  True  True  True]
[[0.9914856 ]
 [0.99543935]
 [0.9881728 ]
 [0.9879483 ]]
[ True  True  True  True]
[[0.99262875]
 [0.99568325]
 [0.9834532 ]
 [0.9790801 ]]
[ True  True  True  True]
[[0.991978  ]
 [0.99571127]
 [0.99290454]
 [0.98646903]]
[ True  True  True  True]
[[0.9936712 ]
 [0.99444133]
 [0.9934729 ]
 [0.9919683 ]]
[ True  True  True  True]
[[0.98607486]
 [0.99554837]
 [0.9925207 ]
 [0.9931473 ]]
[ True  True  True  True]
[[0.9890418]
 [0.9973578]
 [0.9895334]
 [0.9898359]]
[ True  True  True  True]
[[0.98434085]
 [0.99626315]
 [0.99324054]
 [0.9910527 ]]
[ True  True  True  True]
[[0.9892202 ]
 [0.99572325]
 [0.9951517 ]
 [0.9918359 ]]
[ True  True  True  True]
[[0.9894402 