# Task 2: Normalize Breadboard Images

In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
from PIL import Image
import cv2

from breadboard_normalizer.normalizer import Normalizer, PinGrid, draw_corners, resize_width

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
Using Open3D for ICP


In [9]:
normalizer = Normalizer()

Using Open3D for ICP
Creating pingrid with 830 points and 830 labels


In [10]:
image = Image.open('demo_images/train_medium.jpeg')
image = np.asarray(image)

norm, source_corners, conf = normalizer.normalize_image(image)

icp did something, improved score by 18.605569303256672
ransac did something, improved score by 0.03245297239737555
refine off-by-one did something, improved score by 0.0019054780982728538


In [11]:
# visualize the results

annotated = draw_corners(image, source_corners)
annotated = resize_width(annotated, norm.shape[1])

# draw the target pin grid over the top of the image
target = np.zeros_like(norm)
for x, y in normalizer.pingrid.points.astype(int):
    s = int(np.mean(normalizer.pingrid.pitch) / 2) # default normalized dimensions keep grid spacing square
    target = cv2.rectangle(target, (x - s, y - s), (x + s, y + s), (1, 1, 1), 1)

target = (norm * (1 - target) + target * np.array([0, 255, 0])).astype(np.uint8)

stacked = np.vstack([annotated, target])

# cv2 assumes BGR
stacked = np.flip(stacked, axis=-1)
cv2.imshow("demo", stacked)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
# Visualize the orientation detector. Press Q to quit or any other key to advance to the next image.

normalizer.visualize_orientation("demo_images")

[[0.34798062]
 [0.91606903]
 [0.9753713 ]
 [0.9831204 ]]
[False  True  True  True]
[[0.88962   ]
 [0.93346626]
 [0.88485765]
 [0.90901035]]
[ True  True  True  True]
[[0.27501106]
 [0.63345206]
 [0.9709104 ]
 [0.9394519 ]]
[False  True  True  True]
[[0.74235225]
 [0.84128857]
 [0.05098544]
 [0.35973316]]
[ True  True False False]


In [6]:
import cv2
cv2.destroyAllWindows()

In [15]:
import numpy as np

from breadboard_normalizer.normalizer import crop_square, get_source_corners_from_label, reorder_corners, resize_height


def show_demo_image(window_name, normalizer, image):
    image = resize_width(image, 1920)

    norm, detected, score = normalizer.normalize_image(image, registration="icp_ransac", debug=True)

    if norm is None:
        return False

    h, w = image.shape[:2]
    size = np.array([w, h])

    # keypoints = find_keypoints(norm, show_images=True)
    # h = find_homography(keypoints, pingrid, show_images=True)

    image_to_dest = cv2.getPerspectiveTransform(detected, normalizer.destination_corners)

    detected = reorder_corners(detected)

    rough = reorder_corners(normalizer.last_rough_corners)

    centers = (detected + rough) / 2.0

    img_bgr = np.flip(image * 0.75, axis=-1).astype(np.uint8)

    for i in range(4):
        cv2.circle(img_bgr, (int(rough[i][0]), int(rough[i][1])), 4, (0, 0, 255), thickness=-1)
        cv2.circle(img_bgr, (int(detected[i][0]), int(detected[i][1])), 4, (0, 255, 0), thickness=-1)

    norm_bgr = np.flip(norm, axis=-1).astype(np.uint8)

    grid = np.zeros(norm_bgr.shape, dtype=np.uint8)

    p2 = int(np.mean(normalizer.pingrid.pitch) / 2)
    for x, y in normalizer.pingrid.points.astype(int):
        if score >= 0.5:
            grid = cv2.rectangle(grid, (x - p2, y - p2), (x + p2 + 1, y + p2 + 1), (0, 255, 0), 1)
        norm_bgr = cv2.rectangle(norm_bgr, (x - p2, y - p2), (x + p2 + 1, y + p2 + 1), (0, 255, 0), 1)
        
    norm_vert = np.rot90(norm_bgr)

    grid_img = cv2.warpPerspective(grid, np.linalg.inv(image_to_dest), dsize=size)

    crops = []
    for pos in centers:
        crops.append(crop_square(img_bgr, pos.astype(int) - 128, 256))
    
    try:
        mosaic = np.vstack(crops)
    except:
        mosaic = np.zeros((1024, 256, 3), dtype=np.uint8)

    img_bgr = np.clip(grid_img.astype(int) + img_bgr, 0, 255).astype(np.uint8)

    img_bgr = cv2.polylines(img_bgr, [rough.reshape(-1, 1, 2).astype(int)], True, (0, 0, 255), 2, lineType=cv2.LINE_AA)

    if score > 0.5:
        img_bgr = cv2.polylines(img_bgr, [detected.reshape(-1, 1, 2).astype(int)], True, (0, 255, 0), 4, lineType=cv2.LINE_AA)

    img_bgr = resize_height(img_bgr, mosaic.shape[0])

    # img_bgr = np.vstack([img_bgr, mosaic])

    norm_vert = resize_height(norm_vert, mosaic.shape[0])

    img_bgr = np.hstack([mosaic, img_bgr, norm_vert])

    cv2.imshow(window_name, img_bgr)

    if cv2.waitKey(0) == ord('q'):
        return True
    return False


def webcam_offline_demo(webcam_id):
    cap = cv2.VideoCapture(webcam_id)

    if not cap.isOpened():
        print("Error: Could not open webcam.")
        return

    i = 0

    window_name = "Webcam Demo"
    cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)

    while True:
        # 2. Capture frame-by-frame
        # ret is a boolean (True if frame is captured), frame is the image array
        ret, frame = cap.read()

        if not ret:
            print("Error: Can't receive frame. Exiting ...")
            break

        frame_rgb = np.flip(frame, axis=-1)

        key = cv2.waitKey(16)
        if key == ord('q'):
            break
        elif key == ord('s'):
            if show_demo_image("Annotated image 2", normalizer, frame_rgb):
                break
            # annotated = normalizer._visualize_corner_classifier(frame_rgb, window_name)
            # cv2.imshow("annotated screenshot", annotated)
            # cv2.waitKey(0)
            
            # norm, source_corners, score = normalizer.normalize_image(frame_rgb)
            # if norm is None:
            #     continue
            # norm_bgr = np.flip(norm, axis=-1)

            # for x, y in normalizer.pingrid.points:
            #     norm_bgr = cv2.circle(norm_bgr.astype(np.uint8), (int(x), int(y)), 8, (0, 255, 0), -1)

            # cv2.imshow("annotated screenshot", norm_bgr)
            # cv2.waitKey(0)

        cv2.imshow(window_name, frame)
    cv2.destroyAllWindows()





In [14]:
# update this if your webcam is not at id 1
webcam_id = 1

# press 's' to freeze the video feed and show the visualization
webcam_offline_demo(webcam_id)

[[0.98366827]
 [0.9764268 ]
 [0.21084525]
 [0.7170274 ]]
[ True  True False  True]
[[0.98303926]
 [0.94579625]
 [0.43101794]
 [0.9462764 ]]
[ True  True False  True]
[[0.03569964]
 [0.15218754]
 [0.65738153]
 [0.9301999 ]]
[False False  True  True]
[[0.6311132 ]
 [0.03874057]
 [0.40749672]
 [0.8480441 ]]
[ True False False  True]
[[0.02418276]
 [0.02092003]
 [0.11733557]
 [0.03797653]]
[False False False False]
[[0.0385575 ]
 [0.17885284]
 [0.05774019]
 [0.3618173 ]]
[False False False False]
[[0.9616629 ]
 [0.48931223]
 [0.9535184 ]
 [0.9570677 ]]
[ True False  True  True]
[[0.6180898 ]
 [0.709444  ]
 [0.25463003]
 [0.9605231 ]]
[ True  True False  True]
[[0.52004695]
 [0.8681351 ]
 [0.40837345]
 [0.8866277 ]]
[ True  True False  True]
[[0.691844  ]
 [0.6080057 ]
 [0.39332873]
 [0.9865638 ]]
[ True  True False  True]
[[0.6054833 ]
 [0.7247332 ]
 [0.07503652]
 [0.9712099 ]]
[ True  True False  True]
[[0.14964415]
 [0.9666966 ]
 [0.38600895]
 [0.7742449 ]]
[False  True False  True]
[[0.

In [25]:
# to close the frozen windows in the event that the above demo crashes :)
cv2.destroyAllWindows()

# clear an pending events
while cv2.waitKey(1) != -1:
    pass

In [24]:
image = Image.open('demo_images/train_hard.jpeg')
image = np.asarray(image)

show_demo_image("demo", normalizer, image)

icp did something, improved score by 0.013767646470517439
ransac did something, improved score by 0.01906414861616193
refine off-by-one did something, improved score by 0.0005291065671163483


True

In [17]:

# Used to record the video demo. Has not been maintained and now crashes.


def webcam_demo():
    cap = cv2.VideoCapture(1)

    fourcc = cv2.VideoWriter_fourcc(*'mp4v')

    out = None

    if not cap.isOpened():
        print("Error: Could not open webcam.")
        return

    corner_history = np.zeros((4, 4, 2), dtype = np.float32)
    label_history = np.zeros((8), dtype=int)
    i = 0

    window_name = "Webcam Demo"
    cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)

    while True:
        # 2. Capture frame-by-frame
        # ret is a boolean (True if frame is captured), frame is the image array
        ret, frame = cap.read()

        frame_scaled = resize_width(frame, normalizer.target_size[0])

        if not ret:
            print("Error: Can't receive frame. Exiting ...")
            break

        frame_rgb = np.flip(frame, axis=-1)

        annotated = normalizer._visualize_orientation_detector(frame_rgb, window_name)

        if annotated is None:
            continue
        
        if out is None:
            out = cv2.VideoWriter('recordings/output_2.mp4', fourcc, 20.0, (annotated.shape[1], annotated.shape[0]))
        
        out.write(annotated)

        # 4. Press 'q' on the keyboard to exit
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    # 5. Release resources
    cap.release()

    out.release()
    cv2.destroyAllWindows()


In [18]:
webcam_demo()

icp did something, improved score by 1595.0386587964185
ransac did something, improved score by 0.013723823814140583
icp did something, improved score by 1686.769937187358
ransac did something, improved score by 0.013423688548301633
icp did something, improved score by 1534.8460953943736
ransac did something, improved score by 0.013123330192499722


C:\Users\hartley\Documents\School\spring2026\CS470\stage2\project\src\breadboard_normalizer\normalizer.py:516: RuntimeWarning: invalid value encountered in scalar divide
  return np.linalg.norm(src - tgt) / np.sqrt(len(src))


icp did something, improved score by 1832.8954184108397
ransac did something, improved score by 0.013593423137223077
icp did something, improved score by 574.7728469041646
ransac did something, improved score by 0.011821550900315114
refine off-by-one did something, improved score by 2.9613333304459935e-05
